# -*- coding: utf-8 -*-
"""
/***************************************************************************
 forestlabelerDockWidget
                                 A QGIS plugin
 Delineate canopy and label tree 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-06
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Nicholas Rogers
        email                : nickrogers2001@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.core import Qgis, QgsProject, QgsRasterLayer, QgsVectorLayer
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

from .forest_labeler_core.config import (
    CHM_LAYER_NAME,
    SPECIES_POINT_LAYER_NAME,
    TARGET_LAYER_NAME,
)
from .forest_labeler_core.layer_validation import validate_plugin_layers
from .forest_labeler_core.workflows import list_workflows

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'forest_labeler_dockwidget_base.ui'))


class forestlabelerDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, iface=None, parent=None):
        """Constructor."""
        super(forestlabelerDockWidget, self).__init__(parent)
        self.iface = iface
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self._populate_workflows()
        self.workflowComboBox.currentIndexChanged.connect(self._update_workflow_details)
        self.refreshLayersButton.clicked.connect(self.refresh_layers)
        self.validateProjectButton.clicked.connect(self.validate_project)
        self.refresh_layers()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

    def refresh_layers(self):
        """Load current QGIS project layers into the dock controls."""
        self._populate_combo(
            self.chmLayerComboBox,
            self._raster_layers(),
            preferred_name=CHM_LAYER_NAME,
            allow_none=False,
        )
        self._populate_combo(
            self.targetLayerComboBox,
            self._vector_layers(Qgis.GeometryType.Polygon),
            preferred_name=TARGET_LAYER_NAME,
            allow_none=False,
        )
        self._populate_combo(
            self.speciesLayerComboBox,
            self._vector_layers(Qgis.GeometryType.Point),
            preferred_name=SPECIES_POINT_LAYER_NAME,
            allow_none=True,
        )
        self.statusSummaryLabel.setText("Project not validated.")
        self.statusTextEdit.clear()

    def validate_project(self):
        """Validate selected layers and report whether labeling can start."""
        result = validate_plugin_layers(
            self._current_layer(self.chmLayerComboBox),
            self._current_layer(self.targetLayerComboBox),
            self._current_layer(self.speciesLayerComboBox),
        )

        lines = []
        if result.errors:
            lines.append("Errors:")
            lines.extend(f"- {message}" for message in result.errors)
        if result.warnings:
            if lines:
                lines.append("")
            lines.append("Warnings:")
            lines.extend(f"- {message}" for message in result.warnings)

        if result.ok:
            self.statusSummaryLabel.setText("Validation passed. Ready for Phase 2 tool wiring.")
            if not lines:
                lines.append("No validation issues found.")
            self._push_message("Forest Labeler validation passed.", Qgis.Success)
        else:
            self.statusSummaryLabel.setText("Validation failed. Fix project setup before labeling.")
            self._push_message("Forest Labeler validation failed.", Qgis.Warning)

        self.statusTextEdit.setPlainText("\n".join(lines))

    def _populate_workflows(self):
        self.workflowComboBox.blockSignals(True)
        self.workflowComboBox.clear()
        for workflow in list_workflows(include_experimental=True):
            self.workflowComboBox.addItem(workflow.label, workflow.key)
        self.workflowComboBox.blockSignals(False)
        self._update_workflow_details()

    def _current_workflow(self):
        workflow_key = self.workflowComboBox.currentData()
        for workflow in list_workflows(include_experimental=True):
            if workflow.key == workflow_key:
                return workflow
        return None

    def _update_workflow_details(self):
        workflow = self._current_workflow()
        if workflow is None:
            self.workflowMaturityLabel.setText("Select a workflow.")
            self.workflowDescriptionLabel.setText("")
            return

        maturity = "Experimental" if workflow.is_experimental else "Production target"
        write_behavior = "Writes data" if workflow.can_write_data else "Validation only"
        self.workflowMaturityLabel.setText(f"{maturity} - {write_behavior}")

        details = workflow.purpose
        if workflow.readiness_note:
            details = details + "\n" + workflow.readiness_note
        if workflow.experimental_warning:
            details = details + "\n" + workflow.experimental_warning
        self.workflowDescriptionLabel.setText(details)

    def _populate_combo(self, combo, layers, preferred_name, allow_none):
        combo.blockSignals(True)
        combo.clear()

        if allow_none:
            combo.addItem("(none)", None)

        selected_index = 0
        for layer in layers:
            combo.addItem(layer.name(), layer.id())
            if layer.name().lower() == preferred_name.lower():
                selected_index = combo.count() - 1

        combo.setCurrentIndex(selected_index if combo.count() else -1)
        combo.blockSignals(False)

    def _current_layer(self, combo):
        layer_id = combo.currentData()
        if not layer_id:
            return None
        return QgsProject.instance().mapLayer(layer_id)

    def _raster_layers(self):
        return [
            layer
            for layer in QgsProject.instance().mapLayers().values()
            if isinstance(layer, QgsRasterLayer)
        ]

    def _vector_layers(self, geometry_type):
        return [
            layer
            for layer in QgsProject.instance().mapLayers().values()
            if isinstance(layer, QgsVectorLayer) and layer.geometryType() == geometry_type
        ]

    def _push_message(self, message, level):
        if self.iface is not None:
            self.iface.messageBar().pushMessage("Forest Labeler", message, level=level, duration=5)
