# -*- coding: utf-8 -*-
"""
/***************************************************************************
 forestlabeler
                                 A QGIS plugin
 Delineate canopy and label tree 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-06
        copyright            : (C) 2026 by Nicholas Rogers
        email                : nickrogers2001@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load forestlabeler class from file forestlabeler.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .forest_labeler import forestlabeler
    return forestlabeler(iface)
